# Generated by Django 5.1.1 on 2024-10-22 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AirportsDetails', '0002_placestovisit_embed_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='airline',
            name='embed_code',
            field=models.TextField(blank=True, help_text='Paste embed code here (e.g., for YouTube videos, interactive maps, etc.)', null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='embed_code',
            field=models.TextField(blank=True, help_text='Paste embed code here (e.g., for YouTube videos, interactive maps, etc.)', null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='embed_map',
            field=models.TextField(blank=True, help_text='Paste embed map code here', null=True),
        ),
        migrations.AddField(
            model_name='office',
            name='embed_code',
            field=models.TextField(blank=True, help_text='Paste embed code here (e.g., for YouTube videos, interactive maps, etc.)', null=True),
        ),
        migrations.AddField(
            model_name='terminal',
            name='embed_code',
            field=models.TextField(blank=True, help_text='Paste embed code here (e.g., for YouTube videos, interactive maps, etc.)', null=True),
        ),
    ]
