# Generated by Django 5.1.1 on 2024-10-27 01:48

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AirportsDetails', '0003_airline_embed_code_country_embed_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Text')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='services/')),
                ('photo_alt', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='airline',
            name='services_available',
            field=models.ManyToManyField(blank=True, related_name='airlines_services', to='AirportsDetails.services'),
        ),
    ]
