# Generated by Django 5.1.1 on 2024-10-27 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AirportsDetails', '0004_services_airline_services_available'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Services',
            new_name='Service',
        ),
    ]
