# Generated by Django 5.1.1 on 2024-11-01 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AirportsDetails', '0005_rename_services_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='meta_description',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='meta_title',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='airline',
            name='layout',
            field=models.CharField(choices=[('Layout One', 'Layout One'), ('Layout Two', 'Layout Two')], default='Layout Two', max_length=20),
        ),
        migrations.AlterField(
            model_name='airport',
            name='layout',
            field=models.CharField(choices=[('Layout One', 'Layout One'), ('Layout Two', 'Layout Two')], default='Layout Two', max_length=20),
        ),
        migrations.AlterField(
            model_name='office',
            name='layout',
            field=models.CharField(choices=[('Layout One', 'Layout One'), ('Layout Two', 'Layout Two'), ('Layout Heading', 'Layout Heading'), ('Layout Images', 'Layout Images'), ('Layout Reverse', 'Layout Reverse'), ('Layout First 4', 'Layout First 4'), ('Layout First 5', 'Layout First 5'), ('Layout First 6', 'Layout First 6'), ('Layout First 8', 'Layout First 8'), ('Layout From 2 To 6', 'Layout From 2 To 6'), ('Layout From 3 To 7', 'Layout From 3 To 7'), ('Layout From 4 To 8', 'Layout From 4 To 8'), ('Layout Last 3', 'Layout Last 3'), ('Layout Last 4', 'Layout Last 4'), ('Layout Last 5', 'Layout Last 5'), ('Layout Leave 1', 'Layout Leave 1'), ('Layout Leave 2', 'Layout Leave 2'), ('Layout Leave 3', 'Layout Leave 3'), ('Layout Leave 4', 'Layout Leave 4')], default='Layout One', max_length=20),
        ),
        migrations.AlterField(
            model_name='terminal',
            name='layout',
            field=models.CharField(choices=[('Layout One', 'Layout One'), ('Layout Two', 'Layout Two'), ('Layout Heading', 'Layout Heading'), ('Layout Images', 'Layout Images'), ('Layout Reverse', 'Layout Reverse'), ('Layout First 4', 'Layout First 4'), ('Layout First 5', 'Layout First 5'), ('Layout First 6', 'Layout First 6'), ('Layout First 8', 'Layout First 8'), ('Layout From 2 To 6', 'Layout From 2 To 6'), ('Layout From 3 To 7', 'Layout From 3 To 7'), ('Layout From 4 To 8', 'Layout From 4 To 8'), ('Layout Last 3', 'Layout Last 3'), ('Layout Last 4', 'Layout Last 4'), ('Layout Last 5', 'Layout Last 5'), ('Layout Leave 1', 'Layout Leave 1'), ('Layout Leave 2', 'Layout Leave 2'), ('Layout Leave 3', 'Layout Leave 3'), ('Layout Leave 4', 'Layout Leave 4')], default='Layout One', max_length=20),
        ),
    ]
